# Generated by Django 5.2 on 2025-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('icon_class', models.CharField(help_text="Classe Font Awesome, ex. 'fa-heartbeat'", max_length=50, verbose_name='classe icône')),
                ('delay', models.CharField(default='0.1s', help_text="Délai pour l'animation WOW, ex. '0.1s'", max_length=10, verbose_name='délai animation')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
